# Set the base image
FROM node:14

# Set the working directory
WORKDIR usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code
COPY . .

# Expose the port
EXPOSE 3001

# Start the application
CMD [ "node", "app.js" ]
